version: '3.8'

services:
  app:
    container_name: 'fintracer-app'
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "pnpm prisma db push --accept-data-loss && pnpm seed && pnpm dev"
    ports:
      - 3333:3333
    depends_on:
      - fintracer-pg
    environment:
      DATABASE_URL: postgresql://docker:docker@fintracer-pg:5432/fintracerdb?schema=public
      JWT_SECRET: test
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules
    networks:
      - app-net

  fintracer-pg:
    container_name: 'fintracer-pg'
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=fintracerdb
    volumes:
      - fintracer_pg_data:/bitnami/postgresql
    networks:
      - app-net

  prisma-studio:
    container_name: prisma-studio
    image: brunodevcode/docker-prisma-studio
    environment:
      DATABASE_URL: postgresql://docker:docker@fintracer-pg:5432/fintracerdb?schema=public
    ports:
      - 5555:5555
    depends_on:
      - fintracer-pg
    networks:
      - app-net


networks:
  app-net:
    driver: bridge

volumes:
  fintracer_pg_data:
